version: 0.2
env:
  variables:
    NPM_TOKEN: ${NPM_TOKEN}

phases:
  install:
    commands:
      - echo "Install phase"
      - apt-get update -y
      - apt install curl 
      - echo Installing nvm...
      - curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
      - sh ./setup_14.sh
      - apt install nodejs
  pre_build:
    commands:
      - echo "Runnung Tests"
      - npm install
      - npm test
    finally:
      - echo "Run Test finished"
  build:
    commands:
      - echo "Running build command"
      - npm run build
    finally:
      - echo "Run Building finished"
